### PR TITLE
Added table caption tag

### PR DESCRIPTION
**Pull request by jigarmistry**

### CODE REVIEW

**Comment by tryexceptpass** [comment]
You know it's been a long time since I've used this tag and I don't remember it going with any other html object. Googling around seems to confirm that it only applies to `<table>` elements. 

If that's the case, then I'd prefer to implement it as a property of the `Table` object itself. Which would imply adding a new keyword arg to the `__init__` definition and stitching it in at the right place under `__str__`. 

Thanks for the contributions! I appreciate the help.

**Comment by jigarmistry** [comment]
You are right !

But caption tag would have some css style too. How can we manage ?

**Comment by jigarmistry** [comment]
Closing this pull request for...(Some problem with commits)

**Comment by tryexceptpass** [comment]
That's a good point. Let's keep it separate then. You can resubmit whenever you get the commit stuff worked out.

**Pull request closed without merging**
