### PR TITLE
Added Bootstrap Jumbotron, Well

### PR DESCRIPTION
**Pull request by jigarmistry**

### CODE REVIEW

**Comment by tryexceptpass** [comment]
Could you squash your commits please with a `rebase -i` and don't forget to mention the issue numbers on the final summary commit.

**Comment by jigarmistry** [comment]
Still need to add some logic ... Initial draft.. for icons

**Comment by jigarmistry** [comment]
`Could you squash your commits please with a rebase -i and don't forget to mention the issue numbers on the final summary commit.`

How?

**Comment by tryexceptpass** [comment]
You should be able to `git rebase -i master` which will bring up an editor where you can chose how to include your commits. The idea is to `pick` one of your new commits and `squash` the others into it. This cleans up the history into one commit that includes all your changes. Normally GitHub allows me to do this automatically before merging your pull request, but it's not giving me the option this time around (I think because you

Here's a reference: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by jigarmistry** [comment]
Sorry for my mistake... If anything serious please close this PR. I will crate new PR with all changes. Will keep in mind for future.

**Comment by jigarmistry** [comment]
Closing this PR. I will create New PR with all latest changes. If you have any workaround please suggest.

**Pull request closed without merging**
