### PR TITLE
fix: Added a shortcut for generating tag attributes (#73)

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
* Added a modified version of the one in the issue
* Wrote some tests in a new `test/element_test.py` file
* Also added an example/doctest as part of the docstring for the
  `_element_attributes()` function

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
I changed the example in #73 a bit so you are only given a sub-string that you can then add more complicated attributes to. For example:

```
class Footer(Element):
....

    def __str__(self):
        output = [ "<footer" ]

        attributes = [
            ('ident', 'id'),
            ('cl', 'class'),
            ('style', 'style'),
        ]
        sub_str = self._attrs_to_string(attributes)
        output.append(sub_str)

        if self.attrs:
            for k in self.attrs.keys():
                output.append(' ' + k + '="' + self.attrs[k] + '"')

        output.append(">")

        for child in self.children:
            output.append(str(child))

        output.append("</footer>")

        return "".join(output)
```

@tryexceptpass, It doesn't eliminate all the repetition but at least now you only need to handle the special cases. I imagine that a bit of refactoring might even iron out most of those as well.

**Comment by tryexceptpass** [comment]
Looks good, few things I'm thinking about before pulling in though:
* For a good number of items, *attributes* will just be cl and ident. May make sense to have attributes as a keyword arg with a default: `attributes=[('cl','class'), ('ident', 'id')]`.
* I'd like it to handle attributes that don't have values, so if the attribute value is `None`, or maybe something else that makes sense (though not `True` or `False`), it just adds the word to the string. For example: if element has `cl="abc"`, `ident="123"`, `checked=None`, it would translate to `id="123" class="abc" checked`.

**Comment by Michael-F-Bryan** [comment]
I like the idea of adding that default argument. I've added a couple lines and a test to make sure it works.

I don't think I've ever seen/used a tag like `<div id="123" class="abc" checked>` before, but it was a fairly trivial thing to implement and test.

**Comment by tryexceptpass** [comment]
Pulling in... Thanks a lot for the help and suggestions.

On your point about the attributes by themselves, yes they seemed odd to me, but there are a few things in bootstrap that work that way.

**Pull request merged**
